[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Function별 타임아웃 설정
[functions."answer-assemble"]
  timeout = 120

[functions."tax-advisor"]
  timeout = 120

[functions."verify-conflict"]
  timeout = 120

[functions."build-evidence-pack"]
  timeout = 120

[functions."search"]
  timeout = 120

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[dev]
  command = "npm run dev"
  port = 8888
  publish = ".next"
  functions = "netlify/functions"
  targetPort = 3000
